name: Release[1/2] Cut a Release Candidate

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g. 0.1.1rc2)'
        required: true
        type: string
      commit_id:
        description: 'Commit ID for "cut" (default: origin/main)'
        required: false
        type: string
      inference_provider:
        description: 'Inference provider (fireworks, together)'
        required: false
        type: string
        default: 'fireworks'
      cut_mode:
        description: 'Mode to run the script in (test-and-cut, cut-only)'
        type: string
        default: 'test-and-cut'
      llama_stack_only:
        description: 'Only cut a llama-stack release candidate'
        required: false
        type: boolean
        default: false
#  schedule:
#    - cron: "0 0 * * *"  # Run every day at midnight

jobs:
  test-and-cut:
    runs-on: ubuntu-latest
    environment:
      name: testrelease
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: ./actions/test-and-cut
      with:
        version: ${{ inputs.version }}
        commit_id: ${{ inputs.commit_id }}
        inference_provider: ${{ inputs.inference_provider }}
        cut_mode: ${{ inputs.cut_mode }}
        llama_stack_only: ${{ inputs.llama_stack_only }}
        fireworks_api_key: ${{ secrets.FIREWORKS_API_KEY }}
        together_api_key: ${{ secrets.TOGETHER_API_KEY }}
        tavily_search_api_key: ${{ secrets.TAVILY_SEARCH_API_KEY }}
        # TODO: this will expire in 90 days; we should figure out a
        # GitHub App setup that can be used instead
        github_token: ${{ secrets.LLAMA_REPOS_PAT }}

  upload-packages-and-tag:
    needs:
      - test-and-cut
    environment:
      name: testrelease
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: ./actions/upload-packages-and-tag
      with:
        version: ${{ inputs.version }}
        llama_stack_only: ${{ inputs.llama_stack_only }}
        # TODO: this will expire in 90 days; we should figure out a
        # GitHub App setup that can be used instead
        github_token: ${{ secrets.LLAMA_REPOS_PAT }}
        npm_token: ${{ secrets.NPM_TOKEN }}

  test-published-package:
    needs:
      - upload-packages-and-tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./actions/test-published-package
      with:
        version: ${{ inputs.version }}
        inference_provider: ${{ inputs.inference_provider }}
        together_api_key: ${{ secrets.TOGETHER_API_KEY }}
        tavily_search_api_key: ${{ secrets.TAVILY_SEARCH_API_KEY }}
        fireworks_api_key: ${{ secrets.FIREWORKS_API_KEY }}
